# Android

# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
- group: MFVA

steps:

  
- task: appknox.appknox-test.appknox.Appknox@2
  inputs:
    filePath: './app/app-debug.apk'
    accessToken: '97b41feb66834d74acd326ccc5ca48b0cb77a4eb'
    healthScoreThreshold: '90'

