name: QA Signoff Check
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  check-qa-label:
    runs-on: ubuntu-latest
    steps:
      - name: Verify QA label
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'qa-approved') == false
        run: |
          echo "❌ QA approval missing"
          exit 1
